export const locale = {
    lang: 'en',
    data: {
        'CONTENT': {
            'APPLICATIONS': 'Applications',
            'SAMPLE': {
                'TITLE': 'Sample',
                'BADGE': '25'
            },
            'LIST': {
                'TITLE': 'List'
            },
            'MENU': {
                'ORG': 'Organization',
                'USER': 'User',
                'IOTMANAGER': {
                    'IOTMANAGER': 'IoT Manager',
                    'IOTMANAGER_DEVICE_LIST': {
                        'IOTMANAGER_DEVICE_LIST': 'IoT Device List',
                        'REMOTE': 'remote',
                        'REMOTE_DATE': 'Remote Date',
                        'TERMINAL_STATUS': 'Terminal Status',
                        'LOG': 'Log',
                        'CUSTOMER_CD': 'Customer Code',
                        'CUSTOMER_NAME': 'Customer Name',
                        'CUSTOMER_GROUP_CD': 'Customer Group Code',
                        'CUSTOMER_GROUP_NAME': 'Customer Group Name',
                        'CONTRACT_CD': 'Contract Code',
                        'CONTRACT_ITEM_NAME': 'Contract Item Name',
                        'SERIAL_NUM': 'Serial No',
                        'TERMINAL_MODEL_NUMBER': 'Model No',
                        'CONTRACT_STATUS': 'Contract status',
                        'TERMINAL_AVAILABLITY': 'Terminal availability',
                        'PREFECTURES': 'Prefectures',
                        'BRANCH': 'Jurisdiction branch',
                        'DEVICE_UPDATE_DATE': 'Device Update Date',
                        'DEVICE_STATUS': 'Device Status',
                        'DEVICE_LOG': 'Device Log',
                        'REPAIR_REG': 'Repair Reg',
                        'REQ_REPAIR_REG': 'Repair registration request',
                        'CONFIRM_REPAIR_REG': 'Do you want to request repair registration for the device?',
                        'SUCCESS_REPAIR_REG': 'You have successfully requested a repair registration.'
                    },
                    'IOTMANAGER_REMOTE': {
                        'REBOOT': 'Reboot',
                        'SYNC': 'Sync',
                        'DEFAULT_SETTING': 'Default Setting',
                        'DEFAULT_SETTING_FORM': {
                            'COM_PLAN_NAME': 'Plan Name',
                            'COM_REBOOT_ENABLE': 'Reboot Enable',
                            'COM_REBOOT_DATE': 'Reboot, Date',
                            'COM_REBOOT_TIME': 'Reboot Time',
                            'COM_SSID2_NAME': 'SSID2 Name',
                            'COM_SSID2_PASS': 'SSID2 Pass',
                            'COM_SSID2_ENABLE': 'SSID2 Enable',
                            'COM_SSID2_SET1': 'SSID2 Set1',
                            'COM_SSID2_SET2': 'SSID2 Set2',
                            'COM_SSID2_SET3': 'SSID2 Set3',
                            'ENABLED': 'Enabled',
                            'DISABLED': 'Disabled',
                            'DEFAULT': 'DS Default',
                            'MON': 'Monday',
                            'TUE': 'Tuesday',
                            'WED': 'Wednesday',
                            'THU': 'Thursday',
                            'FRI': 'Friday',
                            'SAT': 'Saturday',
                            'SUN': 'Sunday'
                        },
                        'CONFIRM_REBOOT': 'Do you want to reboot the device?',
                        'SUCCESS_REBOOT': 'The device rebooted successfully.',
                        'FAILED_REBOOT': 'It is not a normal connection.',
                        'CONFIRM_SYNC': 'Do you want to synchronize the device?',
                        'SUCCESS_SYNC': 'The device synchronized successfully.',
                        'FAILED_SYNC': 'It is not a normal connection.'
                    }
                },
                'COMMUNICATIONMANAGER': {
                    'COMMUNICATIONMANAGER': 'Communication Manager',
                    'COMMUNICATIONSTATUSUSAGESTATUS': {
                        'COMMUNICATION_DEVICE_LIST': 'Communication Device List',
                        'AGGREGATE': 'Aggregate',
                        'TARGET': 'Target',
                        'CASES': 'Cases',
                        'AGGREGATE_DETAIL': 'Aggregate Detal',
                        'SET_DURATION': 'Duration Setting',
                        'MONTHLY_AGGREGATION': '単月集計',
                        'CUSTOM_AGGREGATION': 'Custom duration',
                        'SELECT_DATES_DESCRIPTION': 'Please select dates to count',
                        'TOTAL': 'Total',
                        'UPLOAD': 'Upload',
                        'DOWNLOAD': 'Download',
                        'COMMUNICATION_CAPACITY': 'Communication Usage',
                        'DAILY': 'Daily',
                        'TIME_UNIT': 'Time',
                        'TIME': 'Time',
                        'CAPACITY': 'Capacity(KB)',
                        'CAPACITY_STACKED': 'Stacked Capacity'
                    },
                    'SPEEDREDUCTIONPAUSEPROCESSING': 'Speed Reduction・Pause',
                    'COMMUNICATION_CONTROL_MANAGER': {
                        'COMMUNICATION_CONTROL_FORM': 'Communication Control Form',
                        'COMMUNICATION_CONTROL_UPDATE': 'Control Update',
                        'COMMUNICATION_CONTROL_STATUS': 'Control Status',
                        'CONTRACT_STATUS': 'Contract Status',
                        'DEVICE_USE_YN': 'Device Usage',
                        'COMMUNICATION_CAPACITY': 'Communication Capacity',
                        'CUSTOMER_CODE': 'Customer Code',
                        'CUSTOMER_NAME': 'Customer Name',
                        'CUSTOMBER_GROUP_CODE': 'Customer Group Code',
                        'CUSTOMBER_GROUP_NAME': 'Coutomer Group Name',
                        'CONTRACT_CODE': 'Contract Code',
                        'CONTRACT_DEVICE_NAME': 'Contract Device Name',
                        'LOCATION_PREFECTURES': 'Location Prefectures',
                        'BRANCH': 'Jurisdiction branch',
                        'DEVICE_UPDATE_DATE': 'Device Update Date',
                        'DEVICE_STATUS': 'Device Status',
                        'EXE_SLOWDOWN': 'Run slower',
                        'STOP_SLOWDOWN': 'Release slowdown',
                        'EXE_SUSPEND': 'Restrict execution',
                        'STOP_SUSPEND': 'Cancel Restrict',
                        'SLOWDOWN_TIME_SETTING': 'Slowdown Time Setting',
                        'TIME_SETTING': 'Time setting',
                        'BOOK_SLOWDOWN': 'Slowing reservation',
                        'BOOK_RESTRICT': 'restriction reservation',
                        'SUCCESS_SLOWDOWN': 'The slowdown setting is complete.',
                        'SUCCESS_RESTRICT': 'The restrict setting is complete.',
                        'CONFIRM_UNLIMIT': 'Do you want to lift the restriction?',
                        'SUCCESS_UNLIMIT': 'Successfully released.',
                        'RESERVATION_EX_TIME': 'Execution time',
                        'STATUS_LACK': 'Please contact your administrator if this condition persists for a long time.'
                    }
                },
                'MOBILEDEVICEMANAGER': {
                    'MOBILEDEVICEMANAGER': 'Mobile Device Manager',
                    'MOBILE_DEVICE_MANAGER': {
                        'CONFIG_SETTING': {
                            'GROUP': {
                                'TITLE': 'Config Group List',
                                'SELECT_GROUP': 'Please select Config group.',
                                'ADDED': 'Add New Group',
                                'ADD_TITLE': 'Config Group Name',
                                'ADD_ERROR': 'Config group name is required',
                                'CHK_POPUP_TITLE': 'Do you want to add a new group?',
                            },
                            'LIST': {
                                'LIST_OF_SETTINGS': 'List of settings',
                                'CONFIG_LIST': 'Config List',
                                'ADD_CONFIG': 'Add Config',
                                'CONFIG_CD': 'Config Code',
                                'CONFIG_NAME': 'Config Name',
                                'VERSION': 'Version',
                                'CHANGE': 'Change',
                                'CREATE': 'Create',
                                'CONFIG_POPUP_TITLE': 'Add New Config Settings',
                                'CONFIG_POPUP_ERROR_NAME': 'Config name required',
                                'CONFIG_POPUP_ERROR_VERSION': 'Config version required',
                                'CHK_POPUP_TITLE': 'Do you want to add Config?',
                                'CHK_POPUP_MODIFY_TITLE': 'Do you want to modify Config?',
                            },
                            'DETAIL': {
                                'CONFIG_SETTING_DETAIL': 'Config Setting Detail',
                                'DEFAULT_SETTINGS': 'Default Settings',
                                'VIEW_SETTINGS': 'View Settings',
                                'PREVIEW': 'Preview',
                                'FREEZE_SETTINGS': 'Freeze settings',
                                'AUTO_WIFI': 'WI-FI Auto connect',
                                'EFFECT': 'Effectiveness',
                                'DISABLED_WIFI': 'Disabled (Allows manual Wi-Fi connection)',
                                'TOOLTIP_1': 'The router that becomes the base unit linked with U∞DS API Automatically set SSID name and password value for SSID1',
                                'SETTING_BLOCK': 'Setting block',
                                'DISABLED_ALLOW_USER': 'Disabled (Allows user to change settings)',
                                'TOOLTIP_2': 'Prevent users from changing Android settings',
                                'MODEL_NAME': 'Model Name',
                                'APP_LIST_SETTINGS': 'App List Settings',
                                'ADD': 'Add',
                                'APP': 'App',
                                'WEB': 'Web shortcuts',
                                'REGISTATION': 'Registration',
                                'CANCEL': 'Cancel',
                                'DELETE': 'Delete',
                                'MODIFY': 'Modify',
                                'SELECT': 'Select',
                                'TARGET_SELECT': 'Target Select',
                                'NAME': 'Name',
                                'VERSION': 'Version',
                                'FILE_UPLOAD': 'File Upload',
                                'WALLPAPER_SETTING': 'Wallpaper Settings',
                                'CANCEL_CONFIG': 'Would you like to go back to the list? The job in progress is canceled.',
                                'ADD_CONFIG': 'Would you like to '
                            }
                        }
                    },
                    'CONFIGSETTING': 'Config Settings',
                    'CONFIG_SETTING': {
                        'SELECT_GROUP': 'Please select confg group',
                        'CONFIG_GROUP': 'Config Group',
                        'CONFIG_LIST': 'Config List',
                        'ADD_CONFIG': 'Add Config',
                        'GROUP_CD': 'Group Code',
                        'GROUP_NAME': 'Group Name',
                        'CONFIG_CD': 'Config Code',
                        'CONFIG_NAME': 'Config Name',
                        'UPDATE_DATE': 'Update Date'
                    },
                    'CONFIGALLOCATION': 'Config Allocation',
                    'CONFIG_ALLOCATION': {
                        'ADD': 'Add',
                        'CONTRACT_CD': 'Contract CD',
                        'CONTRACT_NAME': 'Contract Name',
                        'CONFIG_CD': 'Config CD',
                        'CONFIG_NAME': 'Config Name',
                        'STARTDATE': 'Start Date',
                        'LASTUPDATE': 'Last Update',
                        'ADD_CONFIG_ALLOCATION': 'Add Config Allocation',
                        'SELECT': 'Select',
                        'CANCEL': 'Cancel',
                        'CONTRACT_LIST': 'Contract List',
                        'CONTARCT_CD': 'Contract CD',
                        'DEVICE': 'Device',
                        'SELECT_CONFIG': 'Select Config',
                        'VERSION': 'Version',
                        'DELEVERY_DATE': 'Delivery Date',
                        'COMPLETE_CNT': 'Complete Cnt',
                        'STATUS': 'status',
                        'CONFIRM': 'Confirmation',
                        'CONFIG_CHOOSE': 'Select Config',
                        'CONFIG_GROUP_NAME': 'Config Group Name',
                        'OPERATION': 'Operation',
                        'CANCEL_RESERVATION': 'Cancel',
                        'STATUS_RUNNING': 'Active',
                        'STATUS_RESERVE': 'Reservation',
                        'STATUS_COMPLETE': 'Completion',
                        'SELECT_CONFIG_MODAL': 'Select Config',
                        'CURRENT_CONFIG': 'Current Config',
                        'NEW_BOOKED': 'New Book',
                        'ADJ_BOOK': 'Apply Reservation',
                        'ADJ_HISTORY': 'Apply history',
                        'ALARM_NEW_BOOKED': 'A new reservation has been completed.',
                        'CONFIRM_BOOK_CANCEL': 'Do you want to cancel reservation?',
                        'SUCCESS_BOOK_CANCEL': 'The reservation has been canceled successfully.'
                    },
                    'ORIGINALAPPMANAGEMENT': 'Original App Management',
                    'ORIGINAL_APP_MANAGEMENT': {
                        'APP_LIST': 'App List',
                        'APP_GROUP': 'App Group',
                        'APP_GROUP_ADD': 'App Group Add',
                        'APP_ADD': 'App Add',
                        'UPLOAD_KIND': 'Preloaded original',
                        'CUSTOM': 'custom',
                        'PRELOADED': 'Preloaded original',
                        'NEW_APP_ADDITION': 'New App Add',
                        'APP_VERSION': 'App Version',
                        'PACKAGE_ID': 'Package ID',
                        'PACKAGE_NAME': 'Package Name',
                        'APP_ICON': 'App Icon',
                        'APP_NAME': 'App Name',
                        'REG_DATE': 'Reg Date',
                        'CREATE': 'Create',
                        'CANCEL': 'Cancel'
                    },
                    'PUSHNOTIFICATIONSETTINGS': 'Push Notification Settings',
                    'PUSH_NOTIFICATIONS_SETTING': {
                        'ALARM_ADD': 'Alarm Add',
                        'NOTIFICATION_SETTINGS': 'Notification settings',
                        'ALARM_TARGET': 'Alarm Target',
                        'TARGET_TARGET': 'Target',
                        'COUNT_UNIT': '',
                        'ALL_USERS': 'All users',
                        'CONFIG_SPECIFICATION': 'Sonfig Specification',
                        'CUSTOMER_DESIGNATION': 'Customer contract CD designation',
                        'SELECT_FILE': 'Select contract CD file',
                        'SELECT_CD': 'Select contract CD',
                        'CD_FILE': 'Contract CD File',
                        'NEWS_TITLE': 'News title',
                        'NOTICE_TEXT': 'Notice text',
                        'APP_LINK_SPEC': 'Application link specification',
                        'RESERVATION_DATE': 'Reservation date and time',
                        'ALARM_HISTORY': 'Distribution history',
                        'DELEVARY_DATE': 'Delivery Date',
                        'TITLE': 'Distribution title',
                        'COMP_CNT': 'Number of completed delivery',
                        'STATUS': 'Status',
                        'CANCEL': 'Cancel',
                        'EXISTENCE': 'Yes',
                        'NONE': 'No',
                        'CHK_POPUP_ADD_TITLE': 'Do you want to add Alarm?',
                        'CHK_POPUP_MODIFY_TITLE': 'Do you want to modify Alarm?',
                        'TARGET_COUNT': 'Target Count Query',
                        'TRANS_RESERVATION': 'Delivery Schedule',
                        'CHK_POPUP_MSG': 'Select and click the file.',
                    },
                    'VERSIONUPMANAGEMENT': 'Version UP Management',
                    'AUTOMATICLOCKSETTING': 'Automatic Lock Setting',
                    'AUTOMATIC_LOCK_SETTING': {
                        'AUTOMATIC_LOCK_TIME_SETTING': 'Automatic lock time setting',
                        'EVERYDAY': 'every day',
                        'UPDATE_DESC': 'Applies to devices whose status is newly updated to "unavailable"',
                        'SCREEN_DISPLAY': 'Home screen display setting at automatic lock',
                        'SAVE': 'Save',
                        'CONFIRM_SAVE': 'Do you want to save Auto lock setting?',
                        'UPDATE_SUCCESS': 'Auto lock setting saved.',
                        'RESET_CONTENT': 'Do you want to cancel? The input contents are initialized.'
                    }
                },
                'SETTINGMENU': {
                    'SETTINGMENU': 'Setting',
                    'ORGANIZATION': 'User Manager',
                    'USERMANAGER': 'User Manager',
                    'USER_MANAGER': {
                        'USER_LIST': 'User List',
                        'USER_DETAIL': 'User Detail',
                        'USER_ID': 'User ID',
                        'USER_NAME': 'User Name',
                        'PHONE_NUMBER': 'Phone Number',
                        'E-MAIL': 'E-Mail',
                        'AUTH': 'Auth',
                        'CREATED_DATE': 'Created Date',
                        'DESCRIPTION': 'Description',
                        'SEARCH_PLACEHOLDER': 'Search Keyword',
                        // form
                        'ADD_USER': 'Add User',
                        'MODIFY_USER': 'Modify User',
                        'PASSWORD': 'Password',
                        'CHKPASSWORD': 'Check Password',
                        'MOBILE': 'Mobile',
                        'E_MAIL': 'E-Mail',
                        'MANAGER': 'Admin',
                        'LEADER': 'Leader',
                        'MEMBER': 'Member',
                        'DELETE_USER': 'Delete User',
                        'CONFIRM_DELETE_USER': 'Do you want to delete this user?',
                        'RESET_PWD': 'Reset Password',
                        'CONFIRM_RESET_PWD': 'Do you want to reset password?',
                        'SUCCESS_RESET_PWD': `The user's password reseted successfully`,
                        'RESET_PWD_DESC': 'The temporary password will be issued to the e-mail registered in the member information.',
                        'CHANGE_PWD': 'Change Password',
                        'CONFIRM_CHANGE_PWD': 'Do you want to change password?',
                        'OLD_PWD': 'Old Password',
                        'NEW_PWD': 'New Password',
                        'ERR_MUSTMATCH_PWD': 'It does not match the new password.',
                        'ERR_MUSTDIFFRENT_PWD': 'The new password must be set differently from the current password.',
                        'ERR_ID_MSG': 'UserID can only be written in English. Please write it in 4~20 words.',
                        'ERR_NAME_MSG': 'Please enter your username.',
                        'ERR_PW_MSG': 'Password is not the same. Please re-enter.',
                        'ERR_EMAIL_MSG': 'Not in email format. Please confirm your input.',
                        'ERR_AUTH_MSG': 'No permissions selected. Please choose.',
                        'CHECK_DUP': 'Check Duplication',
                        'CHECK_DUP_ALERT': 'Please check id duplication',
                        'DUP_CHECK_ERR': 'Duplicate Check Failed',
                        'DUP_EMPTY_ID': 'Please input ID.',
                        'DUP_CHECK_SUCCESS': 'The ID is available.',
                        'DUP_CHECK_FAIL': 'The ID already exists.'
                    },
                    'FOTA': {
                        'FOTA': 'FOTA',
                        'PACKAGE': 'Package',
                        'CAMPAIGN': 'Campaign',
                        'VERSION': 'Version',
                        'ADD_PACKAGE': 'Add Package',
                        'SELECT_PACKAGE': 'Select Package',
                        'DESCRIPTION': 'Description',
                        'FILENAME': 'File Name',
                        'ACTIVE': 'Active',
                        'REG_USER_ID': 'Registor',
                        'REG_DATE': 'Registration Date',
                        'TEST': 'TEST',
                        'TEST_PACKAGE': 'Test Package',
                        'SELECT_DEVICE': 'Select Device',
                        'CONFIRM_TEST_PACKAGE': 'Do you want to test the package on this device?',
                        'SUCCESS_TEST_PACKAGE': 'The package test was successful.',
                        'FORCED_ACTIVATION': 'Forced Activation',
                        'CONFIRM_FORCED': 'Do you want to force activate the package without testing it?',
                        'SUCCESS_FORCED': 'The forced Activation was successful.',
                        'BASE_VERSION': 'Base Version',
                        'PACKAGE_TYPE': 'Package Type',
                        'PACKAGE_LIST': 'Package List',
                        'PACKAGE_VERSION_ERR': 'The package version name is required.',
                        'PACKAGE_VERSION': 'Package Version',
                        'ADD_DIFF': 'Create Diff',
                        'PACKAGE_INFO': 'Package Infomation',
                        'TARGET_VERSION': 'Target Version',
                        'TEST_RESULT': 'Test Result',
                        'SUCCESS_TEST': 'The test completed successfully.',
                        'SUCCESS_ACTIVE': 'The packge was activated successfully.',
                        'EXECUTE_TEST': 'Execute Test',
                        'MODIFY_PACKAGE': 'Modify Package',
                        'CONFIRM_MODIFY_PACKAGE': 'Do you want to modify the package?',
                        'SUCCESS_MODIFY_PACKAGE': 'The package was updated successfully.',
                        'CAMPAIGN_INFO': {
                            'ADD': 'Campaign Add',
                            'MODIFY': 'Campaign Modify',
                            'NAME': 'Campaign Name',
                            'DES': 'Description',
                            'PERIOD': 'Period',
                            'PERIOD_TIME': 'Set time during period',
                            'SET_PERIOD': 'Operating hours of the day during the period',
                            'NOT_SETTING_TIME': 'Not setting',
                            'RUN_TIME': 'Execution time',
                            'ACTIVATION': 'Activation',
                            'STATE': 'State',
                            'SUCCESS_COUNT': 'Success Count',
                            'UPDATE_DATE': 'Update Date',
                            'CMP_DEVICE': 'Target Device',
                            'NOTE': 'Note',
                            'PACKAGE_SEL': 'Package Select',
                            'DEVICE_SEL': 'Device Select',
                            'UPDATE_TYPE': 'Update Type',
                            'UPDATE_NONE': 'None',
                            'UPDATE_REG': 'Registration',
                            'PROTOCOL': 'Protocol',
                            'PROTOCOL_HTTP': 'HTTP',
                            'PROTOCOL_HTTPS': 'HTTPS',
                            'NAME_ERROR_MSG': 'Please enter campaign name.',
                            'PACKAGE_ERROR_MSG': 'Please select a package.',
                            'DEVICE_ERROR_MSG': 'Please select a device.',
                            'DESCRIPTION': 'Description',
                            'TITLE': 'Campaign Management',
                            'BASIC_INFO': 'Basic Info',
                            'PACKAGE_NAME': 'Package Name',
                            'USER': 'User ID',
                            'UPDATE_GRAPH': 'Stacked Chart',
                            'STATE_GRAPH': 'Status Chart',
                            'TARGET_LIST': 'Target List',
                            'SUCCESS_LIST': 'Success',
                            'FAIL_LIST': 'Failed',
                            'RUNNING_LIST': 'Running',
                            'LIST': 'LIST',
                            'CAMPAIGN_PERIOD': 'Campaign Period',
                            'UPDATE_TIME_SET': 'Update Set Time',
                            'CONTENT_COUNT': 'Number of products',
                            'RESULT_COUNT': 'Result of success',
                            'DEVICE_NAME': 'Device Name',
                            'TARGET_VERSION': 'Target Version',
                            'CURRENT_VERSION': 'Current Version',
                            'RESULT': 'Result',
                            'DATE': 'Date',
                            'CAMPAIGN_ACTIVATION': 'Activate Campaign',
                            'CAMPAIGN_INACTIVATION': 'Inactivate Campaign',
                            'CONFIRM_ACTIVATION_MSG': 'Do you want to activate the campaign?',
                            'CONFIRM_ACTIVATION_NOT': 'Do you want to inactivate the campaign?',
                            'ACTIVATION_MSG': 'Campaign has been activated.',
                            'ACTIVATION_NOT_MSG': 'Campaign has been disabled.',
                            'ACTIVATION_ERR_MSG': 'Campaign change failed.',
                            'TOTAL': 'Total',
                            'ACCUMULATED': 'Accumulated',
                            'CAMPAIGN_DELETE': 'Do you want to delete the campaign?',
                            'DUPLICATE': 'Duplicate',
                            'CONFIRM_DUPLICATE': 'Do you want to duplicate the campaign?',
                            'SUCCESS_DUPLICATE': 'The campaign has been successfully duplicated.',
                            'CATEGORY': 'Category',
                            'DEVICE_COUNT': 'Total number of selected devices',
                        }
                    }
                },
                'COMMON': {
                    'CHECK': 'Ok',
                    'SAVE': 'Save',
                    'ADD': 'Add',
                    'DELETE': 'Delete',
                    'MODIFY': 'Modify',
                    'SELECT': 'Select',
                    'SUCCESS': 'Success',
                    'FAILED': 'failed',
                    'OK': 'Ok',
                    'CREATE': 'Create',
                    'CANCEL': 'Cancel',
                    'ADD_SUCCESS': 'has been added successfully',
                    'ADD_FAILED': 'Failed to add',
                    'UPDATE_SUCCESS': 'has been updated successfully',
                    'UPDATE_FAILED': 'Failed to update',
                    'DELETE_SUCCESS': 'has been deleted successfully',
                    'DELETE_FAILED': 'Failed to delete',
                    'CONFIRM_SAVE': 'Do you want to Save?',
                    'CONFIRM_ADD': 'Do you want to Add?',
                    'CLOSE_MODAL': 'Close Modal',
                    'CONFIRM_CANCEL_WHRITE': `Do you want to Cancel the write?`,
                    'SEARCH': 'Search',
                    'SEARCH_FIELD': 'Search Field',
                    'CLEAR': 'Clear',
                    'MYPROFILE': 'My Profile',
                    'LOGOUT': 'Logout',
                    'NEXT': 'next',
                    'PREV': 'prev',
                    'COMPLETE': 'Complete',
                    'BAD_REQUEST_PARAM': 'API call format is invalid.',
                    'MISSING_PARAM': 'Some entries are missing',
                    'MDM_APP_GROUP_ALREADY_EXISTS': 'There is already an app group with that name or application ID.',
                    'MDM_APP_GROUP_DOES_NOT_EXISTS': 'No group entered.',
                    'MDM_APP_PACKAGE_ALREADY_EXISTS': 'That version of app package already exists.',
                    'MDM_CONFIG_GROUP_ALREADY_EXISTS': 'There is already a config group with that name.',
                    'MDM_CONFIG_GROUP_DOES_NOT_EXISTS': 'There is no config group entered.',
                    'MDM_CONFIG_ITEM_VERSION_ALREADY_EXISTS': 'There is already a version of config.',
                    'MDM_CONFIG_ITEM_ID_DOES_NOT_EXISTS': 'There is no config item for that ID.',
                    'DEVICETYPE_ITEM_CD_DOES_NOT_EXISTS': 'There is no contract item for the contract CD.',
                    'DOESNOT_EXIST_BY_REQESTED_PARAM': 'The requested value could not be found.',
                    'ALREADY_EXIST_RESERVED_SCHEDULE': 'There is already a reserved config assignment. Cancel your booking and try again.',
                    'FILE_READ_FAILED': 'Failed to read file.',
                    'BAD_REQUEST': 'The request you entered is invalid.',
                    'SERVER_ERROR': 'An error occurred on the server. Contact your administrator.',
                    'FORBIDDEN': 'You do not have permission. Contact your administrator.',
                    'TOKEN_ERROR': 'The session was expired. Please Login.',
                    'LOGIN_ERROR': 'Please check your ID and password',
                    'REQUIRED_FIELD': 'This is required field'
                }
            }
        }
    }
};
