export const locale = {
    lang: 'jp',
    data: {
        'CONTENT': {
            'APPLICATIONS': '用途',
            'SAMPLE': {
                'TITLE': 'サンプル',
                'BADGE': '25'
            },
            'LIST': {
                'TITLE': 'リスト'
            },
            'MENU': {
                'ORG': '組織',
                'USER': 'ユーザー',
                'IOTMANAGER': {
                    'IOTMANAGER': 'IoT Manager',
                    'IOTMANAGER_DEVICE_LIST': {
                        'IOTMANAGER_DEVICE_LIST': 'IoT Device List',
                        'REMOTE': 'リモート',
                        'REMOTE_DATE': 'リモート実行日時',
                        'TERMINAL_STATUS': '端末状態',
                        'LOG': 'ログ',
                        'CUSTOMER_CD': '設置先顧客 CD',
                        'CUSTOMER_NAME': '設置先顧客名',
                        'CUSTOMER_GROUP_CD': '顧客グループ CD',
                        'CUSTOMER_GROUP_NAME': '顧客グループ名',
                        'CONTRACT_CD': '契約 CD',
                        'CONTRACT_ITEM_NAME': '契約品目名',
                        'SERIAL_NUM': 'シリアル No',
                        'TERMINAL_MODEL_NUMBER': '端末型番',
                        'CONTRACT_STATUS': '契約ステータス',
                        'TERMINAL_AVAILABLITY': '端末利用可否',
                        'PREFECTURES': '都道府県',
                        'BRANCH': '管轄支店',
                        'DEVICE_UPDATE_DATE': '端末情報更新日時',
                        'DEVICE_STATUS': '端末ステータス',
                        'DEVICE_LOG': '端末のログ',
                        'REPAIR_REG': '修理登録',
                        'REQ_REPAIR_REG': '修理の登録要求',
                        'CONFIRM_REPAIR_REG': 'Do you want to request repair registration for the device?',
                        'SUCCESS_REPAIR_REG': 'You have successfully requested a repair registration.'
                    },
                    'IOTMANAGER_REMOTE': {
                        'REBOOT': 'リブート',
                        'SYNC': '同期する',
                        'DEFAULT_SETTING': 'デフォルトの設定',
                        'DEFAULT_SETTING_FORM': {
                            'COM_PLAN_NAME': '通信PLAN名',
                            'COM_REBOOT_ENABLE': '定期再起動実施',
                            'COM_REBOOT_DATE': '定期再起動実施曜日',
                            'COM_REBOOT_TIME': '定期再起動実施時間',
                            'COM_SSID2_NAME': 'マルチSSID SSID名',
                            'COM_SSID2_PASS': 'マルチSSID パスワード値',
                            'COM_SSID2_ENABLE': 'マルチSSID 有効／無効',
                            'COM_SSID2_SET1': 'マルチSSID ステルス',
                            'COM_SSID2_SET2': 'マルチSSID プライバシーセパレーター',
                            'COM_SSID2_SET3': 'マルチSSID ネットワークセパレーター',
                            'ENABLED': '有効',
                            'DISABLED': '無効',
                            'DEFAULT': 'DS Default',
                            'MON': '月曜日',
                            'TUE': '火曜日',
                            'WED': '水曜日',
                            'THU': '木曜日',
                            'FRI': '金曜日',
                            'SAT': '土曜日',
                            'SUN': '日曜日'
                        },
                        'CONFIRM_REBOOT': 'Do you want to reboot the device?',
                        'SUCCESS_REBOOT': 'The device rebooted successfully.',
                        'FAILED_REBOOT': 'It is not a normal connection.',
                        'CONFIRM_SYNC': 'Do you want to synchronize the device?',
                        'SUCCESS_SYNC': 'The device synchronized successfully.',
                        'FAILED_SYNC': 'It is not a normal connection.'
                    }
                },
                'COMMUNICATIONMANAGER': {
                    'COMMUNICATIONMANAGER': 'Communication Manager',
                    'COMMUNICATIONSTATUSUSAGESTATUS': {
                        'COMMUNICATION_DEVICE_LIST': 'Communication Device List',
                        'AGGREGATE': '集計',
                        'TARGET': '対象',
                        'CASES': '件',
                        'AGGREGATE_DETAIL': '集計 詳細画面',
                        'SET_DURATION': 'Duration Setting',
                        'MONTHLY_AGGREGATION': '単月集計',
                        'CUSTOM_AGGREGATION': 'Custom duration',
                        'SELECT_DATES_DESCRIPTION': 'Please select dates to count',
                        'TOTAL': '合計',
                        'UPLOAD': '上り',
                        'DOWNLOAD': '下り',
                        'COMMUNICATION_CAPACITY': '通信容量',
                        'DAILY': '日単位',
                        'TIME_UNIT': '時間単位',
                        'TIME': 'Time',
                        'CAPACITY': 'Capacity(KB)',
                        'CAPACITY_STACKED': 'Stacked Capacity'
                    },
                    'SPEEDREDUCTIONPAUSEPROCESSING': '速度低速化、休止処理',
                    'COMMUNICATION_CONTROL_MANAGER': {
                        'COMMUNICATION_CONTROL_FORM': '休止を実行するお客様情報',
                        'COMMUNICATION_CONTROL_UPDATE': '通信制御更新日',
                        'COMMUNICATION_CONTROL_STATUS': '通信制御ステータス',
                        'CONTRACT_STATUS': '契約ステータス',
                        'DEVICE_USE_YN': '端末利用可否',
                        'COMMUNICATION_CAPACITY': '当月の通信容量',
                        'CUSTOMER_CODE': '顧客 CD',
                        'CUSTOMER_NAME': '設置先顧客名',
                        'CUSTOMBER_GROUP_CODE': '顧客グループ CD',
                        'CUSTOMBER_GROUP_NAME': '顧客グループ名',
                        'CONTRACT_CODE': '契約 CD',
                        'CONTRACT_DEVICE_NAME': '契約品目名',
                        'LOCATION_PREFECTURES': '都道府県',
                        'BRANCH': '管轄支店',
                        'DEVICE_UPDATE_DATE': '端末情報更新日時',
                        'DEVICE_STATUS': '端末ステータス',
                        'EXE_SLOWDOWN': '低速化実行',
                        'STOP_SLOWDOWN': '低速化解除',
                        'EXE_SUSPEND': '休止実行',
                        'STOP_SUSPEND': '休止解除',
                        'SLOWDOWN_TIME_SETTING': 'Slowdown Time Setting',
                        'TIME_SETTING': 'Time setting',
                        'BOOK_SLOWDOWN': '低速化の 予約',
                        'BOOK_RESTRICT': '制限 予約',
                        'SUCCESS_SLOWDOWN': 'The slowdown setting is complete.',
                        'SUCCESS_RESTRICT': 'The restrict setting is complete.',
                        'CONFIRM_UNLIMIT': 'Do you want to lift the restriction?',
                        'SUCCESS_UNLIMIT': 'Successfully released.',
                        'RESERVATION_EX_TIME': 'Reservation Execution time',
                        'STATUS_LACK': 'Please contact your administrator if this condition persists for a long time.'
                    }
                },
                'MOBILEDEVICEMANAGER': {
                    'MOBILEDEVICEMANAGER': 'Mobile Device Manager',
                    'MOBILE_DEVICE_MANAGER': {
                        'CONFIG_SETTING': {
                            'GROUP': {
                                'TITLE': 'Config グループ名',
                                'SELECT_GROUP': 'Config グループを選択してください。',
                                'ADDED': '新グループを追加',
                                'ADD_TITLE': 'Config グループ名',
                                'ADD_ERROR': 'Config グループ名は必須です',
                                'CHK_POPUP_TITLE': '新しいグループを追加しますか。',
                            },
                            'LIST': {
                                'LIST_OF_SETTINGS': '設定のリスト',
                                'CONFIG_LIST': 'Config 一覧',
                                'ADD_CONFIG': '新しい Config 設定を追加',
                                'CONFIG_CD': 'Config コード',
                                'CONFIG_NAME': 'Config 名',
                                'VERSION': 'バージョン',
                                'CHANGE': '変更',
                                'CREATE': '作成',
                                'CONFIG_POPUP_TITLE': '新しいConfig設定を追加',
                                'CONFIG_POPUP_ERROR_NAME': 'Config name required',
                                'CONFIG_POPUP_ERROR_VERSION': 'Config version required',
                                'CHK_POPUP_TITLE': 'Do you want to add Config?',
                                'CHK_POPUP_MODIFY_TITLE': 'Do you want to modify Config?',
                            },
                            'DETAIL': {
                                'CONFIG_SETTING_DETAIL': 'Config Setting Detail',
                                'DEFAULT_SETTINGS': 'デフォルトの設定',
                                'VIEW_SETTINGS': '画面の設定',
                                'PREVIEW': '壁紙設定',
                                'FREEZE_SETTINGS': 'OS内各種設定の固定化',
                                'AUTO_WIFI': 'Wi-Fi 自動接続',
                                'EFFECT': '有効',
                                'DISABLED_WIFI': '無効(Wi-Fi の手動接続を許可)',
                                'TOOLTIP_1': 'U∞DS APIで連携された親機となるルータの SSID1のSSID名、パスワード値を自動設定',
                                'SETTING_BLOCK': '設定ブロック',
                                'DISABLED_ALLOW_USER': '無効(ユーザーによる設定変更を許可)',
                                'TOOLTIP_2': 'Androidの設定変更をユーザー側でできないようにする',
                                'MODEL_NAME': '機種名',
                                'APP_LIST_SETTINGS': 'アプリ リスト 設定',
                                'ADD': '追加',
                                'APP': 'アプリ',
                                'WEB': 'WEBショートカット',
                                'REGISTATION': '登録',
                                'CANCEL': 'キャンセル',
                                'DELETE': '削除',
                                'MODIFY': '修正',
                                'SELECT': '登録',
                                'TARGET_SELECT': 'ファイル選択',
                                'NAME': 'Name',
                                'VERSION': 'Version',
                                'FILE_UPLOAD': 'File Upload',
                                'WALLPAPER_SETTING': '壁紙設定',
                                'CANCEL_CONFIG': 'Would you like to go back to the list? The job in progress is canceled.',
                                'ADD_CONFIG': 'Would you like to save config?'
                            }
                        }
                    },
                    'CONFIGSETTING': 'Config 設定',
                    'CONFIG_SETTING': {
                        'CONFIG_GROUP': '設定グループ',
                        'SELECT_GROUP': '設定グループを選択してください',
                        'CONFIG_LIST': '設定のリスト',
                        'ADD_CONFIG': '設定の追加',
                        'GROUP_CD': 'グループ CD',
                        'GROUP_NAME': 'グループ名',
                        'CONFIG_CD': 'コンフィグ CD',
                        'CONFIG_NAME': 'コンフィグ名',
                        'UPDATE_DATE': '更新日'
                    },
                    'CONFIGALLOCATION': 'Config 割当',
                    'CONFIG_ALLOCATION': {
                        'ADD': '追加',
                        'CONTRACT_CD': '契約品目 CD',
                        'CONTRACT_NAME': '契約品目名',
                        'CONFIG_CD': 'Config CD',
                        'CONFIG_NAME': 'Config 名',
                        'STARTDATE': '割当開始日',
                        'LASTUPDATE': '最新更新日',
                        'ADD_CONFIG_ALLOCATION': '品目追加',
                        'SELECT': '選択',
                        'CANCEL': 'キャンセル',
                        'CONTRACT_LIST': '契約品目のリスト',
                        'CONTARCT_CD': '契約品目 CD',
                        'DEVICE': '端末機種',
                        'SELECT_CONFIG': 'Config を選択',
                        'VERSION': 'Config ver.',
                        'DELEVERY_DATE': '配信日時',
                        'COMPLETE_CNT': '配信完了',
                        'STATUS': 'ステータス',
                        'CONFIRM': '確認',
                        'CONFIG_CHOOSE': 'Config を選択',
                        'CONFIG_GROUP_NAME': 'Config グループ名',
                        'OPERATION': '操作',
                        'CANCEL_RESERVATION': 'キャンセル',
                        'STATUS_RUNNING': '活性',
                        'STATUS_RESERVE': '予約',
                        'STATUS_COMPLETE': '完了',
                        'SELECT_CONFIG_MODAL': 'Config選択',
                        'CURRENT_CONFIG': '現在アクティブコンフィグ',
                        'NEW_BOOKED': '新規適用予約',
                        'ADJ_BOOK': '適用予約',
                        'ADJ_HISTORY': '適用履歴',
                        'ALARM_NEW_BOOKED': '新規適用予約が完了しました。',
                        'CONFIRM_BOOK_CANCEL': 'Do you want to cancel reservation?',
                        'SUCCESS_BOOK_CANCEL': 'The reservation has been canceled successfully.'
                    },
                    'ORIGINALAPPMANAGEMENT': 'オリジナル・アプリ管理',
                    'ORIGINAL_APP_MANAGEMENT': {
                        'APP_LIST': '登録プログラムリスト',
                        'APP_GROUP': 'アプリグループ',
                        'APP_GROUP_ADD': 'グループ新規登録',
                        'APP_ADD': '新規登録',
                        'UPLOAD_KIND': 'Preloaded original',
                        'CUSTOM': 'Custom',
                        'PRELOADED': 'Preloaded original',
                        'NEW_APP_ADDITION': '新アプリを追加',
                        'APP_VERSION': 'アプリヴァージョン',
                        'PACKAGE_ID': 'Package ID',
                        'PACKAGE_NAME': 'アプリパッケージ名',
                        'APP_ICON': 'アプリアイコン',
                        'APP_NAME': 'アプリ名',
                        'REG_DATE': '登録日',
                        'CREATE': '作成',
                        'CANCEL': 'キャンセル'
                    },
                    'PUSHNOTIFICATIONSETTINGS': 'プッシュ通知設定',
                    'PUSH_NOTIFICATIONS_SETTING': {
                        'ALARM_ADD': 'Alarm Add',
                        'NOTIFICATION_SETTINGS': '通知設定',
                        'ALARM_TARGET': '通知対象',
                        'TARGET_TARGET': '対象',
                        'COUNT_UNIT': '件',
                        'ALL_USERS': '全利用者',
                        'CONFIG_SPECIFICATION': 'config指定',
                        'CUSTOMER_DESIGNATION': '顧客契約CD指定',
                        'SELECT_FILE': '契約CDファイルを選択',
                        'SELECT_CD': '契約 CD 選択',
                        'CD_FILE': '契約 CD ファイルを選択',
                        'NEWS_TITLE': 'お知らせタイトル',
                        'NOTICE_TEXT': 'お知らせ本文',
                        'APP_LINK_SPEC': 'アプリ・リンク指定',
                        'RESERVATION_DATE': '配信予約日時',
                        'ALARM_HISTORY': '配信履歴',
                        'DELEVARY_DATE': '配信日時',
                        'TITLE': '配信タイトル',
                        'COMP_CNT': '配信完了数',
                        'STATUS': 'ステータス',
                        'CANCEL': 'キャンセル',
                        'EXISTENCE': '有り',
                        'NONE': '無し',
                        'CHK_POPUP_ADD_TITLE': 'Do you want to add Alarm?',
                        'CHK_POPUP_MODIFY_TITLE': 'Do you want to modify Alarm?',
                        'TARGET_COUNT': 'ターゲットカウント照会',
                        'TRANS_RESERVATION': '配達予約',
                        'CHK_POPUP_MSG': 'ファイルを選択してからクリックしてください。',
                    },
                    'VERSIONUPMANAGEMENT': 'ヴァージョンUP 管理',
                    'AUTOMATICLOCKSETTING': '自動ロック設定',
                    'AUTOMATIC_LOCK_SETTING': {
                        'AUTOMATIC_LOCK_TIME_SETTING': '自動ロック時間設定',
                        'EVERYDAY': '毎日',
                        'UPDATE_DESC': 'ステータスが新たに「利用不可」に更新された端末が対象となります',
                        'SCREEN_DISPLAY': '自動ロック時のホーム画面表示設定',
                        'SAVE': '保存',
                        'CONFIRM_SAVE': 'Do you want to save Auto lock setting?',
                        'UPDATE_SUCCESS': 'Auto lock setting saved.',
                        'RESET_CONTENT': 'Do you want to cancel? The input contents are initialized.'
                    }
                },
                'SETTINGMENU': {
                    'SETTINGMENU': 'Setting',
                    'ORGANIZATION': 'ユーザーの管理',
                    'USERMANAGER': 'ユーザーマネージャー',
                    'USER_MANAGER': {
                        'USER_LIST': 'User List',
                        'USER_DETAIL': 'User Detail',
                        'USER_ID': 'User ID',
                        'USER_NAME': 'User Name',
                        'PHONE_NUMBER': 'Phone Number',
                        'E-MAIL': 'E-Mail',
                        'AUTH': 'Auth',
                        'CREATED_DATE': 'Created Date',
                        'DESCRIPTION': 'Description',
                        'SEARCH_PLACEHOLDER': 'Search Keyword',
                        // form
                        'ADD_USER': 'Add User',
                        'MODIFY_USER': 'Modify User',
                        'PASSWORD': 'Password',
                        'CHKPASSWORD': 'Check Password',
                        'MOBILE': 'Mobile',
                        'E_MAIL': 'E-Mail',
                        'MANAGER': '管理者',
                        'LEADER': 'リーダー',
                        'MEMBER': 'メンバー',
                        'DELETE_USER': 'Delete User',
                        'CONFIRM_DELETE_USER': 'Do you want to delete this user?',
                        'RESET_PWD': 'Reset Password',
                        'CONFIRM_RESET_PWD': 'Do you want to reset password?',
                        'SUCCESS_RESET_PWD': `The user's password reseted successfully`,
                        'RESET_PWD_DESC': 'The temporary password will be issued to the e-mail registered in the member information.',
                        'CHANGE_PWD': 'Change Password',
                        'CONFIRM_CHANGE_PWD': 'Do you want to change password?',
                        'OLD_PWD': 'Old Password',
                        'NEW_PWD': 'New Password',
                        'ERR_MUSTMATCH_PWD': 'It does not match the new password.',
                        'ERR_MUSTDIFFRENT_PWD': 'The new password must be set differently from the current password.',
                        'ERR_ID_MSG': 'UserID can only be written in English. Please write it in 4~20 words.',
                        'ERR_NAME_MSG': 'Please enter your username.',
                        'ERR_PW_MSG': 'Password is not the same. Please re-enter.',
                        'ERR_EMAIL_MSG': 'Not in email format. Please confirm your input.',
                        'ERR_AUTH_MSG': 'No permissions selected. Please choose.',
                        'CHECK_DUP': '重複を確認',
                        'CHECK_DUP_ALERT': 'Please check id duplication',
                        'DUP_CHECK_ERR': 'Duplicate Check Failed',
                        'DUP_EMPTY_ID': 'Please input ID.',
                        'DUP_CHECK_SUCCESS': 'The ID is available.',
                        'DUP_CHECK_FAIL': 'The ID already exists.'
                    },
                    'FOTA': {
                        'FOTA': 'FOTA',
                        'PACKAGE': 'Package',
                        'CAMPAIGN': 'Campaign',
                        'VERSION': 'Version',
                        'ADD_PACKAGE': 'Add Package',
                        'SELECT_PACKAGE': 'Select Package',
                        'DESCRIPTION': 'Description',
                        'FILENAME': 'File Name',
                        'ACTIVE': 'Active',
                        'REG_USER_ID': 'Registor',
                        'REG_DATE': 'Registration Date',
                        'TEST': 'TEST',
                        'TEST_PACKAGE': 'Test Package',
                        'SELECT_DEVICE': 'Select Device',
                        'CONFIRM_TEST_PACKAGE': 'Do you want to test the package on this device?',
                        'SUCCESS_TEST_PACKAGE': 'The package test was successful.',
                        'FORCED_ACTIVATION': 'Forced Activation',
                        'CONFIRM_FORCED': 'Do you want to force activate the package without testing it?',
                        'SUCCESS_FORCED': 'The forced Activation was successful.',
                        'BASE_VERSION': 'Base Version',
                        'PACKAGE_TYPE': 'Package Type',
                        'PACKAGE_LIST': 'Package List',
                        'PACKAGE_VERSION_ERR': 'The package version name is required.',
                        'PACKAGE_VERSION': 'Package Version',
                        'ADD_DIFF': 'Create Diff',
                        'PACKAGE_INFO': 'Package Infomation',
                        'TARGET_VERSION': 'Target Version',
                        'TEST_RESULT': 'Test Result',
                        'SUCCESS_TEST': 'The test completed successfully.',
                        'SUCCESS_ACTIVE': 'The package was activated successfully.',
                        'EXECUTE_TEST': 'Execute Test',
                        'MODIFY_PACKAGE': 'Modify Package',
                        'CONFIRM_MODIFY_PACKAGE': 'Do you want to modify the package?',
                        'SUCCESS_MODIFY_PACKAGE': 'The package was updated successfully.',
                        'CAMPAIGN_INFO': {
                            'ADD': 'Campaign Add',
                            'MODIFY': 'Campaign Modify',
                            'NAME': 'Campaign Name',
                            'DES': 'Description',
                            'PERIOD': 'Period',
                            'PERIOD_TIME': 'Set time during period',
                            'SET_PERIOD': 'Operating hours of the day during the period',
                            'NOT_SETTING_TIME': 'Not setting',
                            'RUN_TIME': 'Execution time',
                            'ACTIVATION': 'Activation',
                            'STATE': 'State',
                            'SUCCESS_COUNT': 'Success Count',
                            'UPDATE_DATE': 'Update Date',
                            'CMP_DEVICE': 'Target Device',
                            'NOTE': 'Note',
                            'PACKAGE_SEL': 'Package Select',
                            'DEVICE_SEL': 'Device Select',
                            'UPDATE_TYPE': 'Update Type',
                            'UPDATE_NONE': 'None',
                            'UPDATE_REG': 'Registration', 
                            'PROTOCOL': 'Protocol',
                            'PROTOCOL_HTTP': 'HTTP',
                            'PROTOCOL_HTTPS': 'HTTPS',
                            'NAME_ERROR_MSG': 'Please enter campaign name.',
                            'PACKAGE_ERROR_MSG': 'Please select a package.',
                            'DEVICE_ERROR_MSG': 'Please select a device.',
                            'DESCRIPTION': 'Description',
                            'TITLE': 'Campaign Management',
                            'BASIC_INFO': 'Basic Info',
                            'PACKAGE_NAME': 'Package Name',
                            'USER': 'User ID',
                            'UPDATE_GRAPH': 'Stacked Chart',
                            'STATE_GRAPH': 'Status Chart',
                            'TARGET_LIST': 'Target List',
                            'SUCCESS_LIST': 'Success',
                            'FAIL_LIST': 'Failed',
                            'RUNNING_LIST': 'Running',
                            'LIST': 'LIST',
                            'CAMPAIGN_PERIOD': 'Campaign Period',
                            'UPDATE_TIME_SET': 'Update Set Time',
                            'CONTENT_COUNT': 'Number of products',
                            'RESULT_COUNT': 'Result of success',
                            'DEVICE_NAME': 'Device Name',
                            'TARGET_VERSION': 'Target Version',
                            'CURRENT_VERSION': 'Current Version',
                            'RESULT': 'Result',
                            'DATE': 'Date',
                            'CAMPAIGN_ACTIVATION': 'Activate Campaign',
                            'CAMPAIGN_INACTIVATION': 'Inactivate Campaign',
                            'CONFIRM_ACTIVATION_MSG': 'Do you want to activate the campaign?',
                            'CONFIRM_ACTIVATION_NOT': 'Do you want to inactivate the campaign?',
                            'ACTIVATION_MSG': 'Campaign has been activated.',
                            'ACTIVATION_NOT_MSG': 'Campaign has been disabled.',
                            'ACTIVATION_ERR_MSG': 'Campaign change failed.',
                            'TOTAL': 'Total',
                            'ACCUMULATED': 'Accumulated',
                            'CAMPAIGN_DELETE': 'Do you want to delete the campaign?',
                            'DUPLICATE': 'Duplicate',
                            'CONFIRM_DUPLICATE': 'Do you want to duplicate the campaign?',
                            'SUCCESS_DUPLICATE': 'The campaign has been successfully duplicated.',
                            'CATEGORY': 'Category',
                            'DEVICE_COUNT': 'Total number of selected devices',
                        }
                    }
                },
                'COMMON': {
                    'CHECK': '確認',
                    'SAVE': 'Save',
                    'ADD': 'Add',
                    'DELETE': 'Delete',
                    'MODIFY': 'Modify',
                    'SELECT': '選択',
                    'SUCCESS': '成功',
                    'FAILED': '不合格',
                    'OK': 'はい',
                    'CREATE': '作成',
                    'CANCEL': 'キャンセル',
                    'ADD_SUCCESS': 'has been added successfully',
                    'ADD_FAILED': 'Failed to add',
                    'UPDATE_SUCCESS': 'has been updated successfully',
                    'UPDATE_FAILED': 'Failed to update',
                    'DELETE_SUCCESS': 'has been deleted successfully',
                    'DELETE_FAILED': 'Failed to delete',
                    'CONFIRM_SAVE': 'Do you want to Save?',
                    'CONFIRM_ADD': 'Do you want to Add?',
                    'CLOSE_MODAL': 'Close Modal',
                    'CONFIRM_CANCEL_WHRITE': `Do you want to Cancel the write?`,
                    'SEARCH': 'Search',
                    'SEARCH_FIELD': 'Search Field',
                    'CLEAR': 'Clear',
                    'MYPROFILE': '私のプロフィール',
                    'LOGOUT': 'ログアウト',
                    'NEXT': 'next',
                    'PREV': 'prev',
                    'COMPLETE': 'Complete',
                    'BAD_REQUEST_PARAM': 'API call format is invalid.',
                    'MISSING_PARAM': 'Some entries are missing',
                    'MDM_APP_GROUP_ALREADY_EXISTS': 'There is already an app group with that name or application ID.',
                    'MDM_APP_GROUP_DOES_NOT_EXISTS': 'No group entered.',
                    'MDM_APP_PACKAGE_ALREADY_EXISTS': 'That version of app package already exists.',
                    'MDM_CONFIG_GROUP_ALREADY_EXISTS': 'There is already a config group with that name.',
                    'MDM_CONFIG_GROUP_DOES_NOT_EXISTS': 'There is no config group entered.',
                    'MDM_CONFIG_ITEM_VERSION_ALREADY_EXISTS': 'There is already a version of config.',
                    'MDM_CONFIG_ITEM_ID_DOES_NOT_EXISTS': 'There is no config item for that ID.',
                    'DEVICETYPE_ITEM_CD_DOES_NOT_EXISTS': 'There is no contract item for the contract CD.',
                    'DOESNOT_EXIST_BY_REQESTED_PARAM': 'The requested value could not be found.',
                    'ALREADY_EXIST_RESERVED_SCHEDULE': 'There is already a reserved config assignment. Cancel your booking and try again.',
                    'FILE_READ_FAILED': 'Failed to read file.',
                    'BAD_REQUEST': 'The request you entered is invalid.',
                    'SERVER_ERROR': 'An error occurred on the server. Contact your administrator.',
                    'FORBIDDEN': 'You do not have permission. Contact your administrator.',
                    'TOKEN_ERROR': 'The session was expired. Please Login.',
                    'LOGIN_ERROR': 'Please check your ID and password',
                    'REQUIRED_FIELD': '必須です'
                }
            }
        }
    }
};
