export const locale = {
    lang: 'ko',
    data: {
        'CONTENT': {
            'APPLICATIONS': '어플리케이션',
            'SAMPLE'        : {
                'TITLE': '샘플',
                'BADGE': '25'
            },
            'LIST'          : {
                'TITLE': 'List'
            },
            'MENU'    : {
                'ORG': '조직',
                'USER': '사용자',
                'IOTMANAGER': {
                    'IOTMANAGER': 'IoT 관리자',
                    'IOTMANAGER_DEVICE_LIST': {
                        'IOTMANAGER_DEVICE_LIST': 'IoT 제품 목록',
                        'REMOTE': '원격제어',
                        'REMOTE_DATE': '원격제어 일시',
                        'TERMINAL_STATUS': '터미널 상태',
                        'LOG': '로그',
                        'CUSTOMER_CD': '설치 고객 코드',
                        'CUSTOMER_NAME': '설치 고객 이름',
                        'CUSTOMER_GROUP_CD': '고객 그룹 코드',
                        'CUSTOMER_GROUP_NAME': '고객 그룹 이름',
                        'CONTRACT_CD': '계약코드',
                        'CONTRACT_ITEM_NAME': '계약 품목 이름',
                        'SERIAL_NUM': '시리얼 No',
                        'TERMINAL_MODEL_NUMBER': '모델 No',
                        'CONTRACT_STATUS': '계약 상태',
                        'TERMINAL_AVAILABLITY': '터미널 유효성',
                        'PREFECTURES': '위치(현)',
                        'BRANCH': '영업지점',
                        'DEVICE_UPDATE_DATE': '단말 업데이트 일시',
                        'DEVICE_STATUS': '단말 상태',
                        'DEVICE_LOG': '단말 로그',
                        'REPAIR_REG': '수리 등록',
                        'REQ_REPAIR_REG': '수리 등록 요청',
                        'CONFIRM_REPAIR_REG': '해당 단말을 수리등록 요청 하시겠습니까?',
                        'SUCCESS_REPAIR_REG': '성공적으로 수리등록 요청 하였습니다.'
                    },
                    'IOTMANAGER_REMOTE': {
                        'REBOOT': '재시작',
                        'SYNC': '동기화',
                        'DEFAULT_SETTING': '기본설정',
                        'DEFAULT_SETTING_FORM': {
                            'COM_PLAN_NAME': '플랜 이름',
                            'COM_REBOOT_ENABLE': '재시작 여부',
                            'COM_REBOOT_DATE': '재시작 날짜',
                            'COM_REBOOT_TIME': '재시작 시간',
                            'COM_SSID2_NAME': 'SSID2 이름',
                            'COM_SSID2_PASS': 'SSID2 비밀번호',
                            'COM_SSID2_ENABLE': 'SSID2 여부',
                            'COM_SSID2_SET1': 'SSID2 Set1',
                            'COM_SSID2_SET2': 'SSID2 Set2',
                            'COM_SSID2_SET3': 'SSID2 Set3',
                            'ENABLED': '유효',
                            'DISABLED': '무효',
                            'DEFAULT': 'DS 기본값',
                            'MON': '월요일',
                            'TUE': '화요일',
                            'WED': '수요일',
                            'THU': '목요일',
                            'FRI': '금요일',
                            'SAT': '토요일',
                            'SUN': '일요일'
                        },
                        'CONFIRM_REBOOT': '단말을 재시작 하시겠습니까?',
                        'SUCCESS_REBOOT': '단말을 성공적으로 재시작 하였습니다.',
                        'FAILED_REBOOT': '정상적인 연결 상태가 아닙니다.',
                        'CONFIRM_SYNC': '단말을 동기화 하시겠습니까?',
                        'SUCCESS_SYNC': '단말 동기화에 성공 하였습니다.',
                        'FAILED_SYNC': '정상적인 연결 상태가 아닙니다.',
                    }
                },
                'COMMUNICATIONMANAGER': {
                    'COMMUNICATIONMANAGER': 'Communication 관리자',
                    'COMMUNICATIONSTATUSUSAGESTATUS': {
                        'COMMUNICATION_DEVICE_LIST': 'Communication 제품 목록',
                        'AGGREGATE': '집계',
                        'TARGET': '대상',
                        'CASES': '대',
                        'AGGREGATE_DETAIL': '집계 상세화면',
                        'SET_DURATION': '기간 설정',
                        'MONTHLY_AGGREGATION': '월별 집계',
                        'CUSTOM_AGGREGATION': '기간 설정',
                        'SELECT_DATES_DESCRIPTION': '집계할 날짜를 선택하세요',
                        'TOTAL': '합계',
                        'UPLOAD': '업로드',
                        'DOWNLOAD': '다운로드',
                        'COMMUNICATION_CAPACITY': 'Communication 사용량',
                        'DAILY': '일단위',
                        'TIME_UNIT': '시간단위',
                        'TIME': '시간',
                        'CAPACITY': '사용량(KB)',
                        'CAPACITY_STACKED': '누적량'
                    },
                    'SPEEDREDUCTIONPAUSEPROCESSING': '속도저속화、정지처리',
                    'COMMUNICATION_CONTROL_MANAGER' : {
                        'COMMUNICATION_CONTROL_FORM': '통신 휴지 제어',
                        'COMMUNICATION_CONTROL_UPDATE': '통신 제어 업데이트',
                        'COMMUNICATION_CONTROL_STATUS': '통신 제어 상태',
                        'CONTRACT_STATUS': '계약 상태',
                        'DEVICE_USE_YN': '단말기 사용여부',
                        'COMMUNICATION_CAPACITY': '당월 통신 사용량',
                        'CUSTOMER_CODE': '고객 코드',
                        'CUSTOMER_NAME': '고객 이름',
                        'CUSTOMBER_GROUP_CODE': '고객 그룹 코드',
                        'CUSTOMBER_GROUP_NAME': '고객 그룹 이름',
                        'CONTRACT_CODE': '계약 코드',
                        'CONTRACT_DEVICE_NAME': '계약 품목 이름',
                        'LOCATION_PREFECTURES': '위치(현)',
                        'BRANCH': '관할 지점',
                        'DEVICE_UPDATE_DATE': '단말 업데이트 일시',
                        'DEVICE_STATUS': '단말 상태',
                        'EXE_SLOWDOWN': '저속화 실행',
                        'STOP_SLOWDOWN': '저속화 해제',
                        'EXE_SUSPEND': '휴지 실행',
                        'STOP_SUSPEND': '휴지 해제',
                        'SLOWDOWN_TIME_SETTING': '저속화 시간 설정',
                        'TIME_SETTING': '시간 설정',
                        'BOOK_SLOWDOWN': '저속화 예약',
                        'BOOK_RESTRICT': '휴지 예약',
                        'SUCCESS_SLOWDOWN': '저속화 설정이 완료 되었습니다.',
                        'SUCCESS_RESTRICT': '휴지 실행이 완료 되었습니다.',
                        'CONFIRM_UNLIMIT': '해제 하시겠습니까?',
                        'SUCCESS_UNLIMIT': '성공적으로 해제 되었습니다.',
                        'RESERVATION_EX_TIME': '예약 수행 시간',
                        'STATUS_LACK': '이 상태가 오래 지속되면 관리자에게 문의 하세요.'
                    }
                },
                'MOBILEDEVICEMANAGER': {
                    'MOBILEDEVICEMANAGER': 'Mobile Device 관리자',
                    'MOBILE_DEVICE_MANAGER': {
                        'CONFIG_SETTING': {
                            'GROUP': {
                                'TITLE': 'Config 그룹 목록',
                                'SELECT_GROUP': 'Config 그룹을 선택해주세요.',
                                'ADDED': '새 그룹 추가',
                                'ADD_TITLE': 'Config 그룹 이름',
                                'ADD_ERROR': 'Config 그룹 이름 필요',
                                'CHK_POPUP_TITLE': '새 그룹을 추가 하시겠습니까?',
                            },
                            'LIST': {
                                'LIST_OF_SETTINGS': 'Config 목록',
                                'CONFIG_LIST': 'Config 목록',
                                'ADD_CONFIG': 'Config 추가',
                                'CONFIG_CD': 'Config 코드',
                                'CONFIG_NAME': 'Config 이름',
                                'VERSION': 'Config 버전',
                                'CHANGE': '변경',
                                'CREATE': '생성',
                                'CONFIG_POPUP_TITLE': '새로운 Config 설정 추가',
                                'CONFIG_POPUP_ERROR_NAME': 'Config 이름 필요',
                                'CONFIG_POPUP_ERROR_VERSION': 'Config 버전 필요',
                                'CHK_POPUP_TITLE': 'Config 를 추가 하시겠습니까?',
                                'CHK_POPUP_MODIFY_TITLE': 'Config 정보를 수정 하시겠습니까?',
                            },
                            'DETAIL': {
                                'CONFIG_SETTING_DETAIL': 'Config 설정 상세화면',
                                'DEFAULT_SETTINGS': '기본 설정',
                                'VIEW_SETTINGS': '화면 설정',
                                'PREVIEW': '미리보기',
                                'FREEZE_SETTINGS': 'OS 고정 설정',
                                'AUTO_WIFI': 'Wi-Fi 자동 연결',
                                'EFFECT': '유효',
                                'DISABLED_WIFI': '무효(수동 WI-FI 연결 허용)',
                                'TOOLTIP_1': 'U∞DS API에 연계 된 부모 기가되는 라우터 SSID1의 SSID 이름, 암호 값을 자동 설정합니다.',
                                'SETTING_BLOCK': '설정 블록',
                                'DISABLED_ALLOW_USER': '무효 (사용자 설정 변경 허용)',
                                'TOOLTIP_2': 'Android 설정 변경을 사용자 측에서 할 수 없도록 합니다.',
                                'MODEL_NAME': '모델 이름',
                                'APP_LIST_SETTINGS': '앱 리스트 세팅',
                                'ADD': '추가',
                                'APP': '앱',
                                'WEB': '웹 바로가기',
                                'REGISTATION': '등록',
                                'CANCEL': '취소',
                                'DELETE': '삭제',
                                'MODIFY': '수정',
                                'SELECT': '선택',
                                'TARGET_SELECT': '파일 선택',
                                'NAME': '이름',
                                'VERSION': '버전',
                                'FILE_UPLOAD': '파일 업로드',
                                'WALLPAPER_SETTING': '배경화면 설정',
                                'CANCEL_CONFIG': '목록으로 돌아가시겠습니까? 진행중인 작업은 취소됩니다.',
                                'ADD_CONFIG': '설정을 저장 하시겠습니까?'
                            }
                        }
                    },
                    'CONFIGSETTING': 'Config 설정',
                    'CONFIG_SETTING': {
                        'CONFIG_GROUP': '설정 그룹',
                        'SELECT_GROUP': '설정 그룹을 선택 해 주세요',
                        'CONFIG_LIST': '설정 목록',
                        'ADD_CONFIG': '설정 추가',
                        'GROUP_CD': '그룹 코드',
                        'GROUP_NAME': '그룹 이름',
                        'CONFIG_CD':  '설정 코드',
                        'CONFIG_NAME': '설정 이름',
                        'UPDATE_DATE': '업데이트 일시'
                    },
                    'CONFIGALLOCATION': 'Config 할당',
                    'CONFIG_ALLOCATION': {
                        'ADD': '추가',
                        'CONTRACT_CD': '계약품목 코드',
                        'CONTRACT_NAME': '계약코드 명',
                        'CONFIG_CD': '설정 코드',
                        'CONFIG_NAME': '설정 명',
                        'STARTDATE': '할당 시작일',
                        'LASTUPDATE': '최신 업데이트',
                        'ADD_CONFIG_ALLOCATION': '품목추가',
                        'SELECT': '선택',
                        'CANCEL': '취소',
                        'CONTRACT_LIST': '계약 품목 목록',
                        'CONTARCT_CD': '계약 품목 CD',
                        'DEVICE': '단말기종',
                        'SELECT_CONFIG': '설정 선택',
                        'VERSION':	'버전',
                        'DELEVERY_DATE': '시행일자',
                        'COMPLETE_CNT': '완료수량',
                        'STATUS': '상태',
                        'CONFIRM': '확인',
                        'CONFIG_CHOOSE': 'Config 선택',
                        'CONFIG_GROUP_NAME': 'Config 그룹 이름',
                        'OPERATION': '동작',
                        'CANCEL_RESERVATION': '취소',
                        'STATUS_RUNNING': '활성',
                        'STATUS_RESERVE': '예약',
                        'STATUS_COMPLETE': '완료',
                        'SELECT_CONFIG_MODAL': 'Config 선택',
                        'CURRENT_CONFIG': '현재 활성 Config',
                        'NEW_BOOKED': '신규 적용 예약',
                        'ADJ_BOOK': '적용예약',
                        'ADJ_HISTORY': '적용내역',
                        'ALARM_NEW_BOOKED': '신규 적용 예약이 완료되었습니다.',
                        'CONFIRM_BOOK_CANCEL': '예약을 취소 하시겠습니까?',
                        'SUCCESS_BOOK_CANCEL': '예약이 성공적으로 취소 되었습니다.'
                    },
                    'ORIGINALAPPMANAGEMENT': '오리지날 앱 관리',
                    'ORIGINAL_APP_MANAGEMENT': {
                        'APP_LIST': '등록 프로그램 목록',
                        'APP_GROUP': '앱 그룹',
                        'APP_GROUP_ADD': '앱 그룹 추가',
                        'APP_ADD': '앱 추가',
                        'UPLOAD_KIND': 'Preloaded original' ,
                        'CUSTOM': 'custom',
                        'PRELOADED': 'Preloaded original',
                        'NEW_APP_ADDITION': '새로운 앱 추가',
                        'APP_VERSION': '앱 버전',
                        'PACKAGE_ID': '패키지 ID',
                        'PACKAGE_NAME': '패키지 이름',
                        'APP_ICON': '앱 아이콘',
                        'APP_NAME': '앱 이름',
                        'REG_DATE': '등록일',
                        'CREATE': '생성',
                        'CANCEL': '취소'
                    },
                    'PUSHNOTIFICATIONSETTINGS': '푸쉬알림 세팅',
                    'PUSH_NOTIFICATIONS_SETTING': {
                        'ALARM_ADD': '알림 추가',
                        'NOTIFICATION_SETTINGS': '알림 설정',
                        'ALARM_TARGET': '알림 대상',
                        'TARGET_TARGET': '대상',
                        'COUNT_UNIT': '건',
                        'ALL_USERS': '모든 사용자',
                        'CONFIG_SPECIFICATION': '설정 선택',
                        'CUSTOMER_DESIGNATION': '계약 CD ',
                        'SELECT_FILE': '계약 CD 파일 선택',
                        'SELECT_CD': '계약 CD 선택',
                        'CD_FILE': '계약 CD 파일',
                        'NEWS_TITLE': '알림 제목',
                        'NOTICE_TEXT': '알림 문구',
                        'APP_LINK_SPEC': '앱 링크 지정',
                        'RESERVATION_DATE': '예약 일시',
                        'ALARM_HISTORY': '알림 내역',
                        'DELEVARY_DATE': '예약 일시',
                        'TITLE': '알림 타이틀',
                        'COMP_CNT': '알림 완료 개수',
                        'STATUS': '상태',
                        'CANCEL': '취소',
                        'EXISTENCE': '있음',
                        'NONE': '없음',
                        'CHK_POPUP_ADD_TITLE': '알림을 추가 하시겠습니까?',
                        'CHK_POPUP_MODIFY_TITLE': '알림을 변경 하시겠습니까?',
                        'TARGET_COUNT': '타겟 카운트 조회',
                        'TRANS_RESERVATION': '배달 예약',
                        'CHK_POPUP_MSG': '파일을 선택 후 클릭해주세요.',
                    },
                    'VERSIONUPMANAGEMENT': '버전관리',
                    'AUTOMATICLOCKSETTING': '자동잠금 관리',
                    'AUTOMATIC_LOCK_SETTING': {
                        'AUTOMATIC_LOCK_TIME_SETTING': '자동잠금 시간 설정',
                        'EVERYDAY': '매일',
                        'UPDATE_DESC': '디바이스의 상태가 사용불가로 업데이트 됩니다.',
                        'SCREEN_DISPLAY': '자동 잠금 시 홈 화면 표시',
                        'SAVE': '저장',
                        'CONFIRM_SAVE': '자동잠금 설정을 저장 하시겠습니까?',
                        'UPDATE_SUCCESS': '자동잠금 설정이 저장 되었습니다.',
                        'RESET_CONTENT': '취소 하시겠습니까? 입력중인 값은 초기화 됩니다.'
                    }
                },
                'SETTINGMENU': {
                    'SETTINGMENU': '설정',
                    'ORGANIZATION': '사용자 관리',
                    'USERMANAGER': '사용자 관리',
                    'USER_MANAGER': {
                        'USER_LIST': '사용자 리스트',
                        'USER_DETAIL': '사용자 상세정보',
                        'USER_ID': 'ID',
                        'USER_NAME': '이름',
                        'PHONE_NUMBER': '전화번호',
                        'E-MAIL': '이메일',
                        'AUTH': '권한',
                        'CREATED_DATE': '생성 날짜',
                        'DESCRIPTION': '비고',
                        'SEARCH_PLACEHOLDER': '검색어 입력',
                        // form
                        'ADD_USER': '사용자 추가',
                        'MODIFY_USER': '사용자 정보 수정',
                        'PASSWORD': '비밀번호',
                        'CHKPASSWORD': '비밀번호 확인',
                        'MOBILE': '전화번호',
                        'E_MAIL': 'E-Mail',
                        'MANAGER': '관리자',
                        'LEADER': '리더',
                        'MEMBER': '멤버',
                        'DELETE_USER': '사용자 삭제',
                        'CONFIRM_DELETE_USER': '사용자를 삭제 하시겠습니까?',
                        'RESET_PWD': '비밀번호 초기화',
                        'CONFIRM_RESET_PWD': '비밀번호를 초기화 하시겠습니까?',
                        'SUCCESS_RESET_PWD': '비밀번호가 초기화 되었습니다',
                        'RESET_PWD_DESC': '회원정보에 등록된 E-mail로 임시비밀번호가 발급됩니다.',
                        'CHANGE_PWD': '비밀번호 변경',
                        'CONFIRM_CHANGE_PWD': '비밀번호를 변경 하시겠습니까?',
                        'OLD_PWD': '현재 비밀번호',
                        'NEW_PWD': '새 비밀번호',
                        'ERR_MUSTMATCH_PWD': '새로운 비밀번호와 일치하지 않습니다.',
                        'ERR_MUSTDIFFRENT_PWD': '새 비밀번호는 현재 비밀번호와 다르게 설정해야 합니다.',
                        'ERR_ID_MSG': 'userID 는 영어로만 작성할 수 있습니다. 4~20 자 안으로 작성해주세요.',
                        'ERR_NAME_MSG': '사용자 이름을 입력해주세요.',
                        'ERR_PW_MSG': '비밀번호가 같지 않습니다. 다시 입력해주세요.',
                        'ERR_EMAIL_MSG': 'Email 형식이지 않습니다. 입력을 확인해주세요.',
                        'ERR_AUTH_MSG': '권한을 선택하지 않았습니다. 선택해주세요.',
                        'CHECK_DUP': '중복 확인',
                        'CHECK_DUP_ALERT': 'ID 중복여부를 확인해 주세요',
                        'DUP_CHECK_ERR': '중복체크 실패',
                        'DUP_EMPTY_ID': 'ID를 입력해 주세요.',
                        'DUP_CHECK_SUCCESS': '사용가능한 ID입니다.',
                        'DUP_CHECK_FAIL': '이미 존재하는 ID입니다.'
                    },
                    'FOTA': {
                        'FOTA': 'FOTA',
                        'PACKAGE': '패키지',
                        'CAMPAIGN': '캠페인',
                        'VERSION': '버전',
                        'ADD_PACKAGE': '패키지 등록',
                        'SELECT_PACKAGE': '패키지 선택',
                        'DESCRIPTION': '상세 내용',
                        'FILENAME': '파일 이름',
                        'ACTIVE': '활성화 여부',
                        'REG_USER_ID': '등록자 ID',
                        'REG_DATE': '등록 날짜',
                        'TEST': '테스트',
                        'TEST_PACKAGE': '테스트 패키지',
                        'SELECT_DEVICE': '단말 선택',
                        'CONFIRM_TEST_PACKAGE': '해당 단말에 패키지 테스트를 진행 하시겠습니까?',
                        'SUCCESS_TEST_PACKAGE': '패키지 테스트에 성공 하였습니다.',
                        'FORCED_ACTIVATION': '강제 활성화',
                        'CONFIRM_FORCED': '패키지 테스트 없이 패키지를 활성화 하시겠습니까?',
                        'SUCCESS_FORCED': '패키지 활성화에 성공 하였습니다.',
                        'BASE_VERSION': '베이스 버전',
                        'PACKAGE_TYPE': '패키지 타입',
                        'PACKAGE_LIST': '패키지 목록',
                        'PACKAGE_VERSION_ERR': '패키지 버전명은 필수 입력 사항 입니다.',
                        'PACKAGE_VERSION': '패키지 버전',
                        'ADD_DIFF': 'DIFF 버전 생성',
                        'PACKAGE_INFO': '패키지 정보',
                        'TARGET_VERSION': '대상 버전',
                        'TEST_RESULT': '테스트 결과',
                        'SUCCESS_TEST': '테스트를 성공적으로 완료 하였습니다.',
                        'SUCCESS_ACTIVE': '패키지가 성공적으로 활성화 되었습니다.',
                        'EXECUTE_TEST': '테스트 실행',
                        'MODIFY_PACKAGE': '패키지 수정',
                        'CONFIRM_MODIFY_PACKAGE': '패키지를 수정 하시겠습니까?',
                        'SUCCESS_MODIFY_PACKAGE': '패키지가 성공적으로 수정되었습니다.',
                        'CAMPAIGN_INFO': {
                            'ADD': '캠페인 생성',
                            'MODIFY': '캠페인 수정',
                            'NAME': '캠페인 이름',
                            'DES': '설명',
                            'PERIOD': '기간',
                            'PERIOD_TIME': '기간 중 시간 설정',
                            'SET_PERIOD': '기간에 하루 중 동작 시간',
                            'NOT_SETTING_TIME': '설정하지 않음',
                            'RUN_TIME': '수행시간',
                            'ACTIVATION': '활성화',
                            'STATE': '상태',
                            'SUCCESS_COUNT': '성공 갯수',
                            'UPDATE_DATE': '업데이트 날짜',
                            'CMP_DEVICE': '대상 단말',
                            'NOTE': '비고',
                            'PACKAGE_SEL': '패키지 선택',
                            'DEVICE_SEL': '단말 선택',
                            'UPDATE_TYPE': '업데이트 타입',
                            'UPDATE_NONE': 'None',
                            'UPDATE_REG': 'Registration', 
                            'PROTOCOL': '프로토콜',
                            'PROTOCOL_HTTP': 'HTTP',
                            'PROTOCOL_HTTPS': 'HTTPS',
                            'NAME_ERROR_MSG': '캠페인 이름을 입력해주세요.',
                            'PACKAGE_ERROR_MSG': '패키지를 선택해주세요.',
                            'DEVICE_ERROR_MSG': '디바이스를 선택해주세요.',
                            'DESCRIPTION': '내용',
                            'TITLE': '캠페인 관리',
                            'BASIC_INFO': '기본 정보',
                            'PACKAGE_NAME': '패키지 이름',
                            'USER': '등록자 ID',
                            'UPDATE_GRAPH': '업데이트 추이',
                            'STATE_GRAPH': '상태 분포',
                            'TARGET_LIST': '대상 제품 리스트',
                            'SUCCESS_LIST': '성공',
                            'FAIL_LIST': '실패',
                            'RUNNING_LIST': '진행중',
                            'LIST': '리스트',
                            'CAMPAIGN_PERIOD': '캠페인 기간',
                            'UPDATE_TIME_SET': '업데이트 세팅시간',
                            'CONTENT_COUNT': '제품 수',
                            'RESULT_COUNT': '성공 결과',
                            'DEVICE_NAME': '디바이스 명',
                            'TARGET_VERSION': '대상 버전',
                            'CURRENT_VERSION': '현재 버전',
                            'RESULT': '결과',
                            'DATE': '날짜',
                            'CAMPAIGN_ACTIVATION': '캠페인 활성화',
                            'CAMPAIGN_INACTIVATION': '캠페인 비활성화',
                            'CONFIRM_ACTIVATION_MSG': '캠페인을 활성화 하시겠습니까?',
                            'CONFIRM_ACTIVATION_NOT': '캠페인을 비활설화 하시겠습니까?',
                            'ACTIVATION_MSG': '캠페인이 활성화 되었습니다.',
                            'ACTIVATION_NOT_MSG': '캠페인이 비활성화 되었습니다.',
                            'ACTIVATION_ERR_MSG': '캠페인 변경에 실패하였습니다.',
                            'TOTAL': '전체',
                            'ACCUMULATED': '누적',
                            'CAMPAIGN_DELETE': '캠페인을 삭제 하시겠습니까?',
                            'DUPLICATE': '복제',
                            'CONFIRM_DUPLICATE': '캠페인을 복제 하시겠습니까?',
                            'SUCCESS_DUPLICATE': '캠페인 복제에 성공 하였습니다.',
                            'CATEGORY': '카테고리',
                            'DEVICE_COUNT': '선택된 단말 갯수',
                        }
                    }
                },
                'COMMON': {
                    'CHECK': '확인',
                    'SAVE': '저장',
                    'ADD': '추가',
                    'DELETE': '삭제',
                    'MODIFY': '수정',
                    'SELECT': '선택',
                    'SUCCESS': '성공',
                    'FAILED': '실패',
                    'OK': '예',
                    'CREATE': '생성',
                    'CANCEL': '취소',
                    'ADD_SUCCESS': '성공적으로 추가 하였습니다.',
                    'ADD_FAILED': '추가에 실패 하였습니다.',
                    'UPDATE_SUCCESS': '성공적으로 수정 하였습니다.',
                    'UPDATE_FAILED': '수정에 실패 하였습니다.',
                    'DELETE_SUCCESS': '성공적으로 삭제 하였습니다.',
                    'DELETE_FAILED': '삭제에 실패 하였습니다.',
                    'CONFIRM_SAVE': '저장 하시겠습니까?',
                    'CONFIRM_ADD': '추가 하시겠습니까?',
                    'CLOSE_MODAL': '팝업 종료',
                    'CONFIRM_CANCEL_WHRITE': `입력을 취소 하시겠습니까?`,
                    'SEARCH': '검색',
                    'SEARCH_FIELD': '검색 항목',
                    'CLEAR': '초기화',
                    'MYPROFILE': '프로필',
                    'LOGOUT': '로그아웃',
                    'NEXT': '다음',
                    'PREV': '이전',
                    'COMPLETE': '완료',
                    'BAD_REQUEST_PARAM': 'API 호출  형식이 잘못되었습니다',
                    'MISSING_PARAM': '일부 입력항목이 없습니다',
                    'MDM_APP_GROUP_ALREADY_EXISTS': '해당 이름 또는 application id의 app group이 이미 있습니다',
                    'MDM_APP_GROUP_DOES_NOT_EXISTS': '입력한 group이 없습니다.',
                    'MDM_APP_PACKAGE_ALREADY_EXISTS': '해당 버전의 app package가 이미 있습니다.',
                    'MDM_CONFIG_GROUP_ALREADY_EXISTS': '해당 이름의 config group이 이미 있습니다.',
                    'MDM_CONFIG_GROUP_DOES_NOT_EXISTS': '입력한 config group이 없습니다.',
                    'MDM_CONFIG_ITEM_VERSION_ALREADY_EXISTS': '해당 버전의 config 가 이미 있습니다.',
                    'MDM_CONFIG_ITEM_ID_DOES_NOT_EXISTS': '해당 id의 config item이 없습니다.',
                    'DEVICETYPE_ITEM_CD_DOES_NOT_EXISTS': '해당 계약cd의 계약품목이 없습니다.',
                    'DOESNOT_EXIST_BY_REQESTED_PARAM': '요청한 값을 찾을 수없습니다.',
                    'ALREADY_EXIST_RESERVED_SCHEDULE': '이미 예약된 컨피그 할당이 있습니다. 예약 건을 취소 후 다시 시도하세요.',
                    'FILE_READ_FAILED': '파일 읽기에 실패하였습니다.', 
                    'BAD_REQUEST': '요청하신 입력값이 잘못 되었습니다.',
                    'SERVER_ERROR': '서버에 에러가 발생 하였습니다. 관리자에게 문의하세요.',
                    'FORBIDDEN': '권한이 없습니다. 관리자에게 문의하세요.',
                    'TOKEN_ERROR': '세션이 만료되었습니다. 재로그인 하세요.',
                    'LOGIN_ERROR': '아이디와 비밀번호를 확인 하세요.',
                    'REQUIRED_FIELD': '필수 입력 사항입니다.'
                }
            }
        }
    }
};
